version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            python setup.py install
          name: Install packages
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest
          name: Test
