version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            python setup.py install
          name: Install packages
      - run:
          command: |
            pip install pytest
          name: Install pytest
      - run:
          command: |
            pytest
          name: Test
